# Note: this also includes thoughts on how it should work, not everything is implemented yet
# Used by knega create-chart action, can be overwritten by chartPath in application config (not implemented)
# If neither is set will use Gitlabs auto-deploy-app chart (https://gitlab.com/gitlab-org/charts/auto-deploy-app/) (not implemented)
baseChartPath = "shared/chart"

# Defines where to look for applications
applicationPaths = ["applications", "libraries", "infrastructure"]
applicationSearchDepth = 2

# Worker settings (parallellization is done per app, so no use having more workers than apps)
[Workers]
  # Defaults to number of cpu threads available
  count = 8

# Not implemented (will it ever be?)
# Remote worker settings (amount of simultaneous jobs to be executed on kubernetes cluster)
[RemoteWorkers]
  # Remote workers are disabled by default
  count = 0
  kube_config_path = ""
  kube_context = ""

# Default configuration (used by applications, can be overwritten by app configuration)

# Defines how to check for changes, a hash will be created based on the content of input files
# input paths have $ROOT and $APPLICATION_NAME variable available and are relative to application directory
[Input]
  [Input.Files]
    paths = ["$ROOT/.knega.root.toml"]

  [Input.GitFiles]
    # git ls-files <pattern> (in application directory)
    paths = ["*"]
# everything below has $ROOT, $INPUTS_HASH, $APPLICATION_NAME variables available
[Output]
  [Output.DockerImage]
    # Path of idfile (docker build --iidfile)
    idfile = "container.id"
    # Repository to check whether it was already built or to upload to
    repository = "some-registry.com/some-category/$APPLICATION_NAME"
    tag = "$INPUTS_HASH"
    # Which environment variables to grab username/password from
    # below are hardcoded for now
    # usernameEnv = "KNEGA_DOCKER_USERNAME"
    # passwordEnv = "KNEGA_DOCKER_PASSWORD"

  [Output.HelmChart]
    packageFilePath = ".generated"
    packageFileName = "$APPLICATION_NAME-1.0.0-$INPUTS_HASH.tgz"
    repository = "https://raw.githubusercontent.com/user/repository/master"
    repositoryGitURL = "git@github.com:user/repository.git"
    # below are hardcoded for now
    # usernameEnv = "KNEGA_HELM_USERNAME"
    # passwordEnv = "KNEGA_HELM_PASSWORD"

# knega all check
[Check]
  # working directory: application directory, can run scripts from root using $ROOT_PATH
  commands = [
    "knega test"
  ]

# knega all build
[Build]
  # working directory: application directory, can run scripts from root using $ROOT_PATH
  commands = [
    "knega build",
    "knega chart create",
    "knega docker upload",
    "knega chart upload"
  ]

# knega all analyze
[Analyze]
  # The way I plan on using this is for checks where someone needs to examine the result for it to be worth the compute time
  # and have this action be manually triggered
  onlyChanged = false
  # working directory: application directory, can run scripts from root using $ROOT_PATH
  commands = [
    "knega code-quality",
    "knega dependency-vulnerability",
    "knega container-vulnerability",
    "knega performance",
    "knega generate-report-bundle"
  ]

# knega all release
[Release]
  onlyChanged = false
  # Will run for all applications, regardless of whether it had changes
  # working directory: application directory, can run scripts from root using $ROOT_PATH
  # $INPUTS_HASH is available
  commands = [
    "$ROOT/scripts/release.sh -a $APPLICATION_NAME -h $INPUTS_HASH"
    # "knega release"
  ]
